import Head from 'next/head';
import type { Metadata } from "next";
import { M_PLUS_1_Code } from "next/font/google";
import "./globals.css";
import Navigation from "../components/Navigation";
import Footer from "../components/Footer";
import Script from 'next/script';  // 追加

const m_PLUS_1_Code = M_PLUS_1_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CreatiNext",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=M+PLUS+1+Code:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className={m_PLUS_1_Code.className}>
        <Navigation />
        {children}
        <Footer />
        {/* Google Analyticsのスクリプトを追加 */}
        <Script
          async
          src={`https://www.googletagmanager.com/gtag/js?id=G-2HF45D1J75`}
        />
        <Script
          id="google-analytics"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-2HF45D1J75');
            `,
          }}
        />
      </body>
    </html>
  );
}
